Update to Quarkus 3
redhat-developer-demos/quinoa-wind-turbine pull request #44
Opened 2023-06-15 09:33 UTC by ia3andy

2023-07-01 06:30 UTC, shivam-sharma7 commented on pom.xml
> +    <quarkus-quinoa.version>2.0.5</quarkus-quinoa.version>
```suggestion
    <quarkus-quinoa.version>2.0.6</quarkus-quinoa.version>
```

2023-07-01 06:32 UTC, shivam-sharma7 requested changes

2023-07-01 06:32 UTC, shivam-sharma7 commented on pom.xml
> +    <quarkus-quinoa.version>2.0.5</quarkus-quinoa.version>
update quinoa

2023-07-01 06:32 UTC, shivam-sharma7 commented on pom.xml
> +    <quarkus.platform.version>3.1.1.Final</quarkus.platform.version>
```suggestion
    <quarkus.platform.version>3.1.3.Final</quarkus.platform.version>
```

2023-07-01 06:32 UTC, shivam-sharma7 commented on pom.xml
> +    <quarkus.platform.version>3.1.1.Final</quarkus.platform.version>
update quarkus

2023-09-26 07:52 UTC, kdubois commented
Update to Quarkus 3 already happened in another commit.  Thanks!

2023-09-26 08:58 UTC, ia3andy commented
@kdubois I will update it

2023-09-26 08:58 UTC, merged

2023-09-26 09:04 UTC, ia3andy commented
Ok this seems to be working fine thanks